### ISSUE TITLE
using itkStreamingSinc in combination with itkImageToHistogramFilter

### ISSUE THREAD

**Issue by romangrothausmann** [blowekamp/itkStreamingSinc#2]
Would it be possible to use `itkStreamingSinc` to create a version of `itkImageToHistogramFilter` that is able to stream (similar to [itkStreamingStatisticsImageFilter](https://github.com/blowekamp/itkStreamingSinc/blob/master/include/itkStreamingStatisticsImageFilter.hxx)) or are there complications expected concerning the use of itkHistogram as sinc? A use-case would be for simple CLIs that only report the histogram like https://github.com/romangrothausmann/ITK-CLIs/blob/a926cdcdb1e64cf9020de685be02b64e64b261e0/hist.cxx.

**Comment by blowekamp** [comment]
That is exactly the type of operation the StreamingSinc base class was designed to do. This implementation was for ITKv4, and while it added additional layers to the already complicated pipeline it fits into the concepts well. It would need a little bit of reworking to fit better into the ITKv5 threading models.

**Comment by romangrothausmann** [comment]
Thanks to @blowekamp, this is now available in ITK-5 since https://github.com/InsightSoftwareConsortium/ITK/pull/855.
