### ISSUE TITLE
Update code to support ITKv5 multi-threading model

### ISSUE THREAD

**Issue by jcfr** [blowekamp/itkStreamingSinc#4]
Change similar to https://github.com/InsightSoftwareConsortium/ITK/commit/95640f78b3d2df8ffcb00f299b690d6746f51df2 could be implemented

**Comment by blowekamp** [comment]
This module is quite integrated into the ITK pipeline. It should be worth updating the module.

**Comment by blowekamp** [comment]
The `ImageSinc` base class filter uses the deprecated threading components to multi-thread on the input region of an image filter. It's not clear how to use the new components to do a similar thing.
@dzenanz

**Comment by dzenanz** [comment]
`StreamedGenerateData` and `ThreaderCallback` could be replaced by this definition:
```C++
template <class TInputImage>
void
ImageSinc<TInputImage>
::StreamedGenerateData( unsigned int itkNotUsed(inputRequestedRegionNumber) )
{
  this->GetMultiThreader()->SetNumberOfThreads( this->GetNumberOfThreads() );
  const ThreadIdType  total = this->GetRegionSplitter()->GetNumberOfSplits( m_CurrentInputRegion,  this->GetNumberOfThreads() );
  this->GetMultiThreader()->ParallelizeArray(
    0,
    total,
    [&m_CurrentInputRegion](SizeValueType threadId)
    {
        InputImageRegionType splitRegion = m_CurrentInputRegion;
        this->GetRegionSplitter()->GetSplit( threadId, total, splitRegion );
        this->ThreadedStreamedGenerateData(splitRegion, threadId);
    },
    nullptr); // \Modules\Core\Common\include\itkProgressTransformer.h would need to be used to properly report progress here
}
```
I have not tried to compile this.

**Comment by blowekamp** [comment]
That just about did it! Thanks!
I just had to tweak the capture.

**Comment by romangrothausmann** [comment]
Just stumbled op on this. It is not clear to me what functionality is missing in ITK-5 since the integration of itkStreamingSinc with https://github.com/InsightSoftwareConsortium/ITK/pull/855.

**Comment by romangrothausmann** [comment]
Just noticed that this issue was started before https://github.com/InsightSoftwareConsortium/ITK/pull/855 started. 
@jcfr  @blowekamp issue ready to be closed?

**Comment by jcfr** [comment]
Indeed, it can be closed. Thanks for pointing this out.

@blowekamp Could you update the readme and archive the project ?

**Comment by romangrothausmann** [comment]
> archive the project

As long as ITK-4 is still widely in use, I think the project should not (yet) be archived.

**Comment by jcfr** [comment]
Good point, in that case adding a clarification to the README should be sufficient. Is it something you could help with ?

**Comment by blowekamp** [comment]
Two things missing from ITKv5. 

- The BoundingBox Filter, but that is trivial replaces by using a binary threshold filter and then the streaming label statistics image filter now in ITK.

- The MPI streaming filter is not in ITKv5. It's not been used for a bit. This filter likely should be updated and moved into it's own proper ITK remote module. This filter offers a very unique way to do things in ITK which may be of interest to people as the basis for future work.
