### ISSUE TITLE
Use of itkStreamingSinc broken with newer CMake?

### ISSUE THREAD

**Issue by romangrothausmann** [blowekamp/itkStreamingSinc#6]
Using itkStreamingSinc with ITK-4 used to work (https://gitlab.com/romangrothausmann/ITK-CLIs_GL/-/jobs/205385696) but its compilation with ITK under ubuntu:16.04 lead to:
```
CMake Warning (dev) at Modules/External/itkStreamingSinc/CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```
see https://gitlab.com/romangrothausmann/ITK-CLIs_GL/-/jobs/205385696/raw.
I have the impression that the cmake version in ubuntu:16.04 was changed, now __not__ leading to that warning (https://gitlab.com/romangrothausmann/ITK-CLIs_GL/-/jobs/242806522/raw) but compiling programs making use of itkStreamingSinc now fails with (https://gitlab.com/romangrothausmann/ITK-CLIs_GL/-/jobs/242806522):
```
In file included from /opt/itk/include/ITK-4.13/itkImageSinc.h:112:0,
                 from /opt/itk/include/ITK-4.13/itkStreamingStatisticsImageFilter.h:21,
                 from /code/stat.cxx:14:
/opt/itk/include/ITK-4.13/itkImageSinc.hxx: In instantiation of 'void itk::ImageSinc<TInputImage>::StreamedGenerateData(unsigned int) [with TInputImage = itk::Image<double, 3u>]':
/code/stat.cxx:256:5:   required from here
/opt/itk/include/ITK-4.13/itkImageSinc.hxx:156:3: error: 'itk::ProcessObject::MultiThreaderType {aka class itk::MultiThreader}' has no member named 'SetNumberOfWorkUnits'
   this->GetMultiThreader()->SetNumberOfWorkUnits( this->GetNumberOfWorkUnits() );
   ^
```
even for the very same configuration (https://github.com/romangrothausmann/ITK-CLIs/commit/2cab4b9c385ebac9e32aeec49c6def3a4d1fabcd) that used to work before.

@blowekamp any idea what could be wrong in this case?

**Comment by blowekamp** [comment]
The first is just some CMake version/policy warning that likely can safely be ignored.

The current master of this module was updated for ITKv5 compatibility some what. An older commit is needed. Try: d7d76e1a9196a9138c2156f7c66db98d39cab918

We can that add an "ITKv4" tag to the repo on that hash.

**Comment by romangrothausmann** [comment]
> The current master of this module was updated for ITKv5 compatibility some what. An older commit is needed. Try: d7d76e1

Many thanks for that hint. Works again like a charm (https://gitlab.com/romangrothausmann/ITK-CLIs/-/jobs/244969389). I had been expecting that ITK checks out a fixed commit like it is done for other external modules, but I guess they are treated differently since there cmake also fetches the code with git.

> We can that add an "ITKv4" tag to the repo on that hash.

That would be great, or perhaps even a branch head, which could then serve as a moving ref in case ITK4 compat needs some other adjustment to master in future.

**Comment by blowekamp** [comment]
ITKv5 branch is created. This master branch readme is updates, and filters not in ITKv5 have been removed.
